# Please read https://github.com/holtwick/briefing/blob/master/docs/docker.md for proper use of Docker

services:
  # briefing:
  #   image: holtwick/briefing
  #   restart: always
  #   volumes:
  #     - ./data:/app/data
  #   ports:
  #     - 8999:8080

  #   environment:
  #     - MUTE_VIDEO=1
  #     - MUTE_AUDIO=0
  #     - SHOW_FULLSCREEN=1
  #     - SHOW_INVITATION=1
  #     - SHOW_INVITATION_HINT=1
  #     - SHOW_SETTINGS=1
  #     - SHOW_SHARE=1
  #     - SHOW_CHAT=1

  #   labels:
  #     - 'traefik.enable=true'
  #     - 'traefik.http.routers.meeting-iamon99-http.rule=Host(`meeting.iamon99.com`)'
  #     - 'traefik.http.routers.meeting-iamon99-http.entrypoints=web'
  #     - 'traefik.http.routers.meeting-iamon99-http.middlewares=meeting-https'
  #     - 'traefik.http.middlewares.meeting-iamon99-https.redirectscheme.scheme=https'
  #     - 'traefik.http.routers.meeting-iamon99-https.rule=Host(`meeting.iamon99.com`)'
  #     - 'traefik.http.routers.meeting-iamon99-https.entrypoints=websecure'
  #     - 'traefik.http.routers.meeting-iamon99-https.tls.certresolver=myresolver'
  #     - 'traefik.http.services.meeting-iamon99-https.loadbalancer.server.port=8080'

  mongodb:
    image: docker.io/bitnami/mongodb:5.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  express:
    image: docker.io/bitnami/express:4
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongodb:27017/myapp
      - EXPRESS_SKIP_DB_WAIT=0
      - EXPRESS_SKIP_DB_MIGRATION=0
      - EXPRESS_SKIP_NPM_INSTALL=0
      - EXPRESS_SKIP_BOWER_INSTALL=0
    volumes:
      - '../express-src:/app'
    depends_on:
      - mongodb
    env_file:
      - ../express-src/.env

    # command: npm run development
# networks:
#   default:
#     external:
#       name: traefik-proxy-network
